<?php
/**
 * Router script for PHP's built-in development server.
 *
 * The bare `php -S localhost:8080 -t public` serves any request whose path
 * has a recognized file extension (.xml, .txt, .json, …) as a static file —
 * and 404s if that file doesn't exist, WITHOUT ever reaching index.php. That
 * breaks routes like /sitemap.xml and /robots.txt, which are generated by
 * the app rather than served as static files. Passing this script as the
 * server's router fixes it: real static files (css/js/images) are still
 * served directly, everything else falls through to public/index.php,
 * matching how the Apache .htaccess rewrite rule behaves in production.
 *
 * Usage: php -S localhost:8080 -t public router.php
 */

declare(strict_types=1);

$publicDir = __DIR__ . '/public';
$path      = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?? '/';
$file      = $publicDir . $path;

if ($path !== '/' && is_file($file)) {
    return false; // let the built-in server serve the static file as-is
}

// For a path with an extension (e.g. /event/x/calendar.ics) the built-in
// server sets SCRIPT_NAME to that path, which makes Request::getPath() strip
// "/event/x" as if it were the app's base directory. Everything is routed
// through public/index.php, so say so.
$_SERVER['SCRIPT_NAME'] = '/index.php';

require $publicDir . '/index.php';
